---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - wl_app
    attributes:
      wl_app:
        client_name: foobar_ltd
