name             'wl_app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wl_app'
long_description 'Installs/Configures wl_app'
version          '0.1.0'

depends 'wlw_zlib'
depends 'nginx'
