---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - wl_base
    attributes:
      authorization:
        sudo:
          users:
            - vagrant
          passwordless: true
