name             'wl_base'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wl_base'
long_description 'Installs/Configures wl_base'
version          '0.1.0'

depends 'openssh'
depends 'ntp'
depends 'sysstat'
depends 'users'
depends 'sudo'
depends 'zsh'
